apply plugin: 'com.android.library'

android {
    namespace 'com.anonymous.frontend.llama'
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        
        ndk {
            abiFilters "arm64-v8a", "x86_64"
        }
    }

    externalNativeBuild {
        cmake {
            path "../app/src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
